provider:
  name: faas
  gateway: https://faas.srv.locational.io
functions:
  sleepy:
    lang: ruby
    handler: ./sleepy
    image: onlyjsmith/sleepy:0.0.1
    environment:
      read_timeout: 60
      write_timeout: 60
      exec_timeout: 65
